// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp.Data;

public partial class Bilet
{
    public int Id { get; set; }

    public int? Posetitel { get; set; }

    public int? Vistavka { get; set; }

    public DateTime? VisitDate { get; set; }

    public double? Cost { get; set; }

    public virtual Posetiteli PosetitelNavigation { get; set; }

    public virtual Vistavki VistavkaNavigation { get; set; }
}