// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp.Data;

public partial class Posetiteli
{
    public int Id { get; set; }

    public string Familiya { get; set; }

    public string Imya { get; set; }

    public DateTime? Datebirth { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Bilet> Bilets { get; set; } = new List<Bilet>();
}